import {
  useNavigate,
  useRouteContext,
  useRouter,
  useSearch,
} from '@tanstack/react-router'
import { useEffect, useRef, useState } from 'react'
import { useChat } from '@ai-sdk/react'
import { v4 as uuidv4 } from 'uuid'
import { DefaultChatTransport } from 'ai'
import { toast } from 'sonner'
import type { AppUIMessage } from '@/lib/ai-sdk/types'
import { Messages } from '@/features/chat/ui/components/chat-messages'
import { MultiModalInput } from '@/features/chat/ui/components/chat-multimodal-input'
import { ChatHeader } from '@/features/chat/ui/components/chat-header'
import { useSelectedModel } from '@/features/chat/ui/components/chat-model-selector'

interface ChatInterfaceProps {
  id: string
  initialMessages: AppUIMessage[]
}

export const ChatInterface = ({ id, initialMessages }: ChatInterfaceProps) => {
  const [input, setInput] = useState<string>('')
  const [selectedModel] = useSelectedModel()
  const selectedModelRef = useRef(selectedModel)
  selectedModelRef.current = selectedModel
  const hasAppendedQueryRef = useRef(false)
  const hasAutoGeneratedRef = useRef(false)

  const { orpc, queryClient } = useRouteContext({ strict: false })
  const router = useRouter()
  const { query, autoGenerate } = useSearch({ strict: false })
  const navigate = useNavigate()

  const { sendMessage, messages, status, regenerate, stop } =
    useChat<AppUIMessage>({
      id,
      messages: initialMessages,
      generateId: uuidv4,
      transport: new DefaultChatTransport({
        api: '/api/ai/chat',
        prepareSendMessagesRequest: (request) => {
          const lastMessage = request.messages.at(-1)

          return {
            body: {
              id: request.id,
              message: lastMessage,
              modelId: selectedModelRef.current,
              ...request.body,
            },
          }
        },
      }),
      onFinish: () => {
        void queryClient?.invalidateQueries(orpc?.chats.getAll.queryOptions())
      },
      onError: (error) => {
        console.error(error)
        toast.error('Failed to generate response', {
          description: error.message,
        })
      },
    })

  // handle browser back/forward navigation
  useEffect(() => {
    const handlePopState = () => {
      // When user navigates back/forward, refresh to sync with URL
      void router.invalidate()
    }

    window.addEventListener('popstate', handlePopState)
    return () => {
      window.removeEventListener('popstate', handlePopState)
    }
  }, [router])

  useEffect(() => {
    if (query && !hasAppendedQueryRef.current) {
      // Set ref immediately (synchronous) to prevent double execution
      hasAppendedQueryRef.current = true

      // Send the message from the query param (passed from homepage navigation)
      void sendMessage({
        role: 'user' as const,
        parts: [{ type: 'text', text: query }],
      })

      // Clean up the query param from URL without adding history entry
      void navigate({
        to: `/chat/$chatId`,
        params: { chatId: id },
        replace: true,
        viewTransition: true,
      })
    }
  }, [query, sendMessage, id])

  // Auto-generate response when branching from a user message
  useEffect(() => {
    if (autoGenerate && !hasAutoGeneratedRef.current) {
      const lastMessage = initialMessages.at(-1)
      if (!lastMessage) return

      if (lastMessage.role === 'user') {
        hasAutoGeneratedRef.current = true
        void regenerate()
      }

      // Clean up the autoGenerate param from URL
      void navigate({
        to: `/chat/$chatId`,
        params: { chatId: id },
        replace: true,
        viewTransition: true,
      })
    }
  }, [autoGenerate, initialMessages, regenerate, id, navigate])

  return (
    <div className="absolute top-0 bottom-0 w-full">
      <ChatHeader />
      <div className="absolute right-0 bottom-2 left-0 z-10 mx-auto flex w-full max-w-3xl gap-2 px-4">
        <MultiModalInput
          chatId={id}
          input={input}
          setInput={setInput}
          status={status}
          stop={stop}
          messages={messages}
          sendMessage={sendMessage}
        />
      </div>

      <Messages
        chatId={id}
        messages={messages}
        status={status}
        regenerate={regenerate}
        key={id}
      />
    </div>
  )
}
